apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test-app-ns
spec:
  replicas: {{ .Values.replicasCount }}
  selector: 
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: {{ .Values.imageName }}
        imagePullPolicy: IfNotPresent   # to aviod pulling image from registry
        env:
        - name: AUTHOR
          value: {{ .Values.author }}
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /hc
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /hc
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        
